In [1]:
import numpy as nump
from numpy import argmax
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential

In [2]:
data=load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
x=data.data[:,:].astype('float32')
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y=data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.10)

In [6]:
n_feature=x_train.shape[1]
n_feature

4

In [7]:
model=Sequential()

In [8]:
model.add(Dense(10,activation='relu',kernel_initializer='he_normal',input_shape=(n_feature,)))
model.add(Dense(9,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(3,activation='softmax'))

In [9]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [10]:
model.fit(x_train,y_train,epochs=100,batch_size=30)

Epoch 1/100
5/5 [==============================] - 2s 12ms/step - loss: 1.8259 - accuracy: 0.3185
Epoch 2/100
5/5 [==============================] - 0s 4ms/step - loss: 1.7216 - accuracy: 0.3185
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 1.6232 - accuracy: 0.3185
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 1.5323 - accuracy: 0.3185
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 1.4527 - accuracy: 0.3185
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 1.3909 - accuracy: 0.3185
Epoch 7/100
5/5 [==============================] - 0s 4ms/step - loss: 1.3321 - accuracy: 0.3185
Epoch 8/100
5/5 [==============================] - 0s 6ms/step - loss: 1.2834 - accuracy: 0.3185
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 1.2408 - accuracy: 0.3185
Epoch 10/100
5/5 [==============================] - 0s 4ms/step - loss: 1.2008 - accuracy: 0.3185
Epoch 11/100
5/5 [==========

In [11]:
new_data=[2.3,5.6,1.2,3]

In [12]:
y_pred=model.predict([new_data])
y_pred

1/1 [==============================] - 0s 115ms/step


array([[0.28459698, 0.00626155, 0.70914143]], dtype=float32)

In [13]:
acc_score=model.evaluate(x_test,y_test)
acc_score

1/1 [==============================] - 0s 146ms/step - loss: 0.5113 - accuracy: 0.8000


[0.511264979839325, 0.800000011920929]